import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

export interface InitScriptSigningValues {
  storeFile: string;
  storePassword: string;
  keyAlias: string;
  keyPassword: string;
}

export interface InitScriptOptions {
  signing: InitScriptSigningValues;
  /** Build type whose signingConfig is overridden (usually "release"). */
  buildType: string;
  versionCode?: number;
  versionName?: string;
}

function groovyLiteral(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/**
 * Renders a Gradle init script that overrides signing (and optionally the
 * version) of the Android application module from the outside, so project
 * files never need caricamento-specific wiring and may be regenerated at any
 * time (e.g. `expo prebuild --clean`).
 *
 * The override runs in afterEvaluate, which is registered before the project
 * build script is evaluated — AGP reads the model in its own later
 * afterEvaluate callbacks, so the injected values win over whatever the
 * project template hardcodes (e.g. signingConfigs.debug for release).
 */
export function renderGradleInitScript(options: InitScriptOptions): string {
  const { signing, buildType } = options;
  const lines = [
    '// Generated by caricamento. Do not edit; regenerated on every build.',
    'gradle.allprojects { project ->',
    '    project.afterEvaluate {',
    "        def androidExt = project.extensions.findByName('android')",
    '        if (androidExt == null) {',
    '            return',
    '        }',
    '        androidExt.signingConfigs {',
    '            caricamento {',
    `                storeFile project.file(${groovyLiteral(signing.storeFile)})`,
    `                storePassword ${groovyLiteral(signing.storePassword)}`,
    `                keyAlias ${groovyLiteral(signing.keyAlias)}`,
    `                keyPassword ${groovyLiteral(signing.keyPassword)}`,
    '            }',
    '        }',
    '        androidExt.buildTypes.all { buildType ->',
    `            if (buildType.name == ${groovyLiteral(buildType)}) {`,
    '                buildType.signingConfig = androidExt.signingConfigs.caricamento',
    '            }',
    '        }',
  ];
  if (options.versionCode !== undefined) {
    lines.push(`        androidExt.defaultConfig.versionCode = ${options.versionCode}`);
  }
  if (options.versionName !== undefined) {
    lines.push(`        androidExt.defaultConfig.versionName = ${groovyLiteral(options.versionName)}`);
  }
  lines.push('    }', '}');
  return lines.join('\n') + '\n';
}

export interface InitScriptHandle {
  path: string;
  cleanup: () => Promise<void>;
}

/**
 * Writes the init script to a private temp file (0600 — it contains the
 * keystore passwords in plaintext). Callers MUST invoke cleanup() once the
 * Gradle process has exited.
 */
export async function writeGradleInitScript(script: string): Promise<InitScriptHandle> {
  const dir = await mkdtemp(join(tmpdir(), 'caricamento-init-'));
  const path = join(dir, 'caricamento.init.gradle');
  await writeFile(path, script, { mode: 0o600 });
  return {
    path,
    cleanup: () => rm(dir, { recursive: true, force: true }),
  };
}
